mod 'puppet-nginx', '1.1.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/stdlib'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker', '3.10.0'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
